# universal functions

In [6]:
#universal functions are simple mathematics function
#universal functions are objects those belongs to numpy.ufunc class.
#ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements
#Converting iterative statements into a vector based operation is called vectorization.
#Vectorization is used to speed up the Python code without using loop

In [1]:
import time

In [31]:
a = [1, 2, 3]
b = [5, 6, 7]
z=[]
for i,j in zip(a,b):
    z.append(i+j)
    
print(z)

[6, 8, 10]


In [12]:
import numpy as np

# simple arithmetics

In [18]:
a = np.random.randint(9, size=5)

In [19]:
a

array([2, 2, 2, 3, 5])

In [20]:
b = np.random.randint(9, size = 5)

In [21]:
b

array([2, 4, 3, 0, 3])

In [29]:
import time

In [30]:
start = time.time()
addt = np.add(a,b)
print(addt)
end = time.time()
print(end - start)

[4 6 5 3 8]
0.0


In [16]:
b =  np.random.randint(9, size = 5)

In [9]:
b

array([5, 1, 5, 7, 5])

In [7]:
a = [5, 8, 2, 8, 5]
b = [5, 1, 5, 7, 5]
c = [6, 7, 8, 1, 2]

# 1.addittion

In [11]:
addt = np.add(a,b,)

NameError: name 'np' is not defined

In [11]:
addt

array([10,  9,  7, 15, 10])

# 2.subraction 

In [14]:
subt = np.subtract(a,b)
subt

array([ 0,  7, -3,  1,  0])

# 3.multiplication

In [15]:
mult = np.multiply(a,b)
mult

array([25,  8, 10, 56, 25])

# 4.division

In [17]:
div = np.divide(a,b)
div

array([1.        , 8.        , 0.4       , 1.14285714, 1.        ])

# 5.power

In [18]:
por = np.power(a,b)
por

array([   3125,       8,      32, 2097152,    3125], dtype=int32)

# 6.absolute value

In [19]:
arr1 = [1, -2, 0, -9]
newarr = np.absolute(arr1)
newarr

array([1, 2, 0, 9])

# truncation

In [21]:
arry = [-0.346849, 3.5769]
trun = np.trunc(arry)
trun

array([-0.,  3.])

In [22]:
fic = np.fix(arry)
fic

array([-0.,  3.])

# rounding

In [24]:
ron = np.around(arry)
ron

array([-0.,  4.])

# Summation

In [40]:
ar = np.random.randint(9, size = 3)

In [30]:
ar

array([7, 2, 5])

In [39]:
s = np.sum(ar)
s

14

In [34]:
# cummulative sum - partially adding the elements in array.
cs = np.cumsum(ar)
cs

array([ 7,  9, 14], dtype=int32)

In [45]:
ar1 = np.random.randint(9, size = 3)
ar1

array([5, 8, 5])

In [47]:
#axis sum
newarr = np.sum([ar1, ar], axis=1)
newarr

array([18,  3])

# Set Operations

# 1.unique

In [49]:
arr1 =[1, 1, 1, 2, 2, 4, 4, 7, 7, 7, 7, 8]

In [50]:
new = np.unique(arr1)

In [51]:
new

array([1, 2, 4, 7, 8])

# 2.union

In [56]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

In [57]:
ar = np.union1d(arr1, arr2)
ar

array([1, 2, 3, 4, 5, 6])

# 3.intersection

In [61]:
n = np.intersect1d(arr1, arr2)
n

array([3, 4])

# 4.difference

In [ ]:
#find only the values in the first set that is NOT present in the seconds set

In [62]:
dif = np.setdiff1d(arr1,arr2)
dif

array([1, 2])

# 5.symmetric diference

In [67]:
ar =  np.setxor1d(arr1, arr2, assume_unique=True)
ar

array([1, 2, 5, 6])

# trignometric function

In [75]:
arr = np.array([90, 180, 270, 360])
a = np.deg2rad(arr)
a

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [76]:
x = np.sin(a)
x

array([ 1.0000000e+00,  1.2246468e-16, -1.0000000e+00, -2.4492936e-16])

In [77]:
x = np.sin(np.pi/2)
x

1.0

# hypotenues

In [79]:
base = 10
prep = 15
hyp = np.hypot(base,prep)
hyp

18.027756377319946

In [80]:
#hyperbolic function

# statistical function

In [83]:
height = [150, 168.9, 170, 191, 185.7, 177.5]

In [85]:
Min = np.min(height)
Min

150.0

In [86]:
Max = np.max(height)
Max

191.0

In [88]:
#percentile
y = np.percentile(height, 80)
y

185.7

In [90]:
x = np.mean(height)
x

173.85

In [91]:
z = np.median(height)
z

173.75

In [92]:
a = np.std(height)
a

13.266593383382183

In [23]:
arr = np.array([3.6, 3.4])

In [24]:
truarr = np.trunc(arr)

In [25]:
truarr

array([3., 3.])

In [26]:
a = np.around(arr)

In [27]:
a

array([4., 3.])